### ISSUE TITLE
Update list of media fields

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_riprap#35]
https://github.com/mjordan/islandora_riprap/blob/master/src/Riprap/IslandoraRiprapUtils.php#L32 doesn't contain all the media fields used by Islandora (the document media's fieldname is missing, for example).

**Comment by elizoller** [comment]
Do you want a PR for this? I'm keen on having it fixed because its affecting our production environment.

**Comment by mjordan** [comment]
`$media_fields` should be a config option, which would allow sites to add their own. I am happy to add a textarea to the admin settings form with the existing list of fields, one per line, as the default. But, if you have time to open a PR for that, yes, a PR would be nice. But if that's too much, I can do it ASAP (like this evening). Let me know.

**Comment by elizoller** [comment]
the earliest i'd be able to get to it would be this evening as well.

**Comment by mjordan** [comment]
If you agree with the approach I describe, and have time, go for it! Or, let me know otherwise.

**Comment by elizoller** [comment]
pull request is here: https://github.com/mjordan/islandora_riprap/pull/37

**Comment by mjordan** [comment]
Resolved with 0e1e0743932b8adcc231fdb693b9337aa9ef669c.
